import { SlOptions } from "react-icons/sl";

const Data=[
    {
        sno: 1,
        activity: "PF Remittance",
        formname: "PF Challan",
        applicablelaw: "Provident Fund & Miscellaneous Act, 1952",
        acttype: "Central",
        duedate: "15 of every Month",
        period: "Monthly",
        section: "Payment Receipt",
        priority: "High",
      },
      {
        sno: 2,
        activity: "PF Remittance",
        formname: "Form-2 / E-nomination",
        applicablelaw: "Employee State Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "Annual",
        section: "Preserve Form 2",
        priority: "Medium",
      },
      {
        sno: 3,
        activity: "PF",
        formname: "Form-3",
        applicablelaw: "Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "monthly",
        section: "Preserve Form 2",
        priority: "high",
      },
      {
        sno: 4,
        activity: "PF return",
        formname: "Form-4",
        applicablelaw: "Insurance Act, 1998",
        acttype: "state",
        duedate: "monthly",
        period: "monthly",
        section: "Preserve Form 3",
        priority: "low",
      },
      {
        sno: 1,
        activity: "PF Remittance",
        formname: "PF Challan",
        applicablelaw: "Provident Fund & Miscellaneous Act, 1952",
        acttype: "Central",
        duedate: "15 of every Month",
        period: "Monthly",
        section: "Payment Receipt",
        priority: "High",
      },
      {
        sno: 2,
        activity: "PF Remittance",
        formname: "Form-2 / E-nomination",
        applicablelaw: "Employee State Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "Annual",
        section: "Preserve Form 2",
        priority: "Medium",
      },
      {
        sno: 3,
        activity: "PF",
        formname: "Form-3",
        applicablelaw: "Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "monthly",
        section: "Preserve Form 2",
        priority: "high",
      },
      {
        sno: 4,
        activity: "PF return",
        formname: "Form-4",
        applicablelaw: "Insurance Act, 1998",
        acttype: "state",
        duedate: "monthly",
        period: "monthly",
        section: "Preserve Form 3",
        priority: "low",
      },
      {
        sno: 1,
        activity: "PF Remittance",
        formname: "PF Challan",
        applicablelaw: "Provident Fund & Miscellaneous Act, 1952",
        acttype: "Central",
        duedate: "15 of every Month",
        period: "Monthly",
        section: "Payment Receipt",
        priority: "High",
      },
      {
        sno: 2,
        activity: "PF Remittance",
        formname: "Form-2 / E-nomination",
        applicablelaw: "Employee State Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "Annual",
        section: "Preserve Form 2",
        priority: "Medium",
      },
      {
        sno: 3,
        activity: "PF",
        formname: "Form-3",
        applicablelaw: "Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "monthly",
        section: "Preserve Form 2",
        priority: "high",
      },
      {
        sno: 4,
        activity: "PF return",
        formname: "Form-4",
        applicablelaw: "Insurance Act, 1998",
        acttype: "state",
        duedate: "monthly",
        period: "monthly",
        section: "Preserve Form 3",
        priority: "low",
      },
      {
        sno: 1,
        activity: "PF Remittance",
        formname: "PF Challan",
        applicablelaw: "Provident Fund & Miscellaneous Act, 1952",
        acttype: "Central",
        duedate: "15 of every Month",
        period: "Monthly",
        section: "Payment Receipt",
        priority: "High",
      },
      {
        sno: 2,
        activity: "PF Remittance",
        formname: "Form-2 / E-nomination",
        applicablelaw: "Employee State Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "Annual",
        section: "Preserve Form 2",
        priority: "Medium",
      },
      {
        sno: 3,
        activity: "PF",
        formname: "Form-3",
        applicablelaw: "Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "monthly",
        section: "Preserve Form 2",
        priority: "high",
      },
      {
        sno: 4,
        activity: "PF return",
        formname: "Form-4",
        applicablelaw: "Insurance Act, 1998",
        acttype: "state",
        duedate: "monthly",
        period: "monthly",
        section: "Preserve Form 3",
        priority: "low",
      },
      {
        sno: 1,
        activity: "PF Remittance",
        formname: "PF Challan",
        applicablelaw: "Provident Fund & Miscellaneous Act, 1952",
        acttype: "Central",
        duedate: "15 of every Month",
        period: "Monthly",
        section: "Payment Receipt",
        priority: "High",
      },
      {
        sno: 2,
        activity: "PF Remittance",
        formname: "Form-2 / E-nomination",
        applicablelaw: "Employee State Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "Annual",
        section: "Preserve Form 2",
        priority: "Medium",
      },
      {
        sno: 3,
        activity: "PF",
        formname: "Form-3",
        applicablelaw: "Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "monthly",
        section: "Preserve Form 2",
        priority: "high",
      },
      {
        sno: 4,
        activity: "PF return",
        formname: "Form-4",
        applicablelaw: "Insurance Act, 1998",
        acttype: "state",
        duedate: "monthly",
        period: "monthly",
        section: "Preserve Form 3",
        priority: "low",
      },
      {
        sno: 1,
        activity: "PF Remittance",
        formname: "PF Challan",
        applicablelaw: "Provident Fund & Miscellaneous Act, 1952",
        acttype: "Central",
        duedate: "15 of every Month",
        period: "Monthly",
        section: "Payment Receipt",
        priority: "High",
      },
      {
        sno: 2,
        activity: "PF Remittance",
        formname: "Form-2 / E-nomination",
        applicablelaw: "Employee State Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "Annual",
        section: "Preserve Form 2",
        priority: "Medium",
      },
      {
        sno: 3,
        activity: "PF",
        formname: "Form-3",
        applicablelaw: "Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "monthly",
        section: "Preserve Form 2",
        priority: "high",
      },
      {
        sno: 4,
        activity: "PF return",
        formname: "Form-4",
        applicablelaw: "Insurance Act, 1998",
        acttype: "state",
        duedate: "monthly",
        period: "monthly",
        section: "Preserve Form 3",
        priority: "low",
      },
      {
        sno: 1,
        activity: "PF Remittance",
        formname: "PF Challan",
        applicablelaw: "Provident Fund & Miscellaneous Act, 1952",
        acttype: "Central",
        duedate: "15 of every Month",
        period: "Monthly",
        section: "Payment Receipt",
        priority: "High",
      },
      {
        sno: 2,
        activity: "PF Remittance",
        formname: "Form-2 / E-nomination",
        applicablelaw: "Employee State Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "Annual",
        section: "Preserve Form 2",
        priority: "Medium",
      },
      {
        sno: 3,
        activity: "PF",
        formname: "Form-3",
        applicablelaw: "Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "monthly",
        section: "Preserve Form 2",
        priority: "high",
      },
      {
        sno: 4,
        activity: "PF return",
        formname: "Form-4",
        applicablelaw: "Insurance Act, 1998",
        acttype: "state",
        duedate: "monthly",
        period: "monthly",
        section: "Preserve Form 3",
        priority: "low",
      },
      {
        sno: 1,
        activity: "PF Remittance",
        formname: "PF Challan",
        applicablelaw: "Provident Fund & Miscellaneous Act, 1952",
        acttype: "Central",
        duedate: "15 of every Month",
        period: "Monthly",
        section: "Payment Receipt",
        priority: "High",
      },
      {
        sno: 2,
        activity: "PF Remittance",
        formname: "Form-2 / E-nomination",
        applicablelaw: "Employee State Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "Annual",
        section: "Preserve Form 2",
        priority: "Medium",
      },
      {
        sno: 3,
        activity: "PF",
        formname: "Form-3",
        applicablelaw: "Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "monthly",
        section: "Preserve Form 2",
        priority: "high",
      },
      {
        sno: 4,
        activity: "PF return",
        formname: "Form-4",
        applicablelaw: "Insurance Act, 1998",
        acttype: "state",
        duedate: "monthly",
        period: "monthly",
        section: "Preserve Form 3",
        priority: "low",
      },
      {
        sno: 1,
        activity: "PF Remittance",
        formname: "PF Challan",
        applicablelaw: "Provident Fund & Miscellaneous Act, 1952",
        acttype: "Central",
        duedate: "15 of every Month",
        period: "Monthly",
        section: "Payment Receipt",
        priority: "High",
      },
      {
        sno: 2,
        activity: "PF Remittance",
        formname: "Form-2 / E-nomination",
        applicablelaw: "Employee State Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "Annual",
        section: "Preserve Form 2",
        priority: "Medium",
      },
      {
        sno: 3,
        activity: "PF",
        formname: "Form-3",
        applicablelaw: "Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "monthly",
        section: "Preserve Form 2",
        priority: "high",
      },
      {
        sno: 4,
        activity: "PF return",
        formname: "Form-4",
        applicablelaw: "Insurance Act, 1998",
        acttype: "state",
        duedate: "monthly",
        period: "monthly",
        section: "Preserve Form 3",
        priority: "low",
      },

      {
        sno: 1,
        activity: "PF Remittance",
        formname: "PF Challan",
        applicablelaw: "Provident Fund & Miscellaneous Act, 1952",
        acttype: "Central",
        duedate: "15 of every Month",
        period: "Monthly",
        section: "Payment Receipt",
        priority: "High",
      },
      {
        sno: 2,
        activity: "PF Remittance",
        formname: "Form-2 / E-nomination",
        applicablelaw: "Employee State Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "Annual",
        section: "Preserve Form 2",
        priority: "Medium",
      },
      {
        sno: 3,
        activity: "PF",
        formname: "Form-3",
        applicablelaw: "Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "monthly",
        section: "Preserve Form 2",
        priority: "high",
      },
      {
        sno: 4,
        activity: "PF return",
        formname: "Form-4",
        applicablelaw: "Insurance Act, 1998",
        acttype: "state",
        duedate: "monthly",
        period: "monthly",
        section: "Preserve Form 3",
        priority: "low",
      },
      {
        sno: 1,
        activity: "PF Remittance",
        formname: "PF Challan",
        applicablelaw: "Provident Fund & Miscellaneous Act, 1952",
        acttype: "Central",
        duedate: "15 of every Month",
        period: "Monthly",
        section: "Payment Receipt",
        priority: "High",
      },
      {
        sno: 2,
        activity: "PF Remittance",
        formname: "Form-2 / E-nomination",
        applicablelaw: "Employee State Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "Annual",
        section: "Preserve Form 2",
        priority: "Medium",
      },
      {
        sno: 3,
        activity: "PF",
        formname: "Form-3",
        applicablelaw: "Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "monthly",
        section: "Preserve Form 2",
        priority: "high",
      },
      {
        sno: 4,
        activity: "PF return",
        formname: "Form-4",
        applicablelaw: "Insurance Act, 1998",
        acttype: "state",
        duedate: "monthly",
        period: "monthly",
        section: "Preserve Form 3",
        priority: "low",
      },
      {
        sno: 1,
        activity: "PF Remittance",
        formname: "PF Challan",
        applicablelaw: "Provident Fund & Miscellaneous Act, 1952",
        acttype: "Central",
        duedate: "15 of every Month",
        period: "Monthly",
        section: "Payment Receipt",
        priority: "High",
      },
      {
        sno: 2,
        activity: "PF Remittance",
        formname: "Form-2 / E-nomination",
        applicablelaw: "Employee State Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "Annual",
        section: "Preserve Form 2",
        priority: "Medium",
      },
      {
        sno: 3,
        activity: "PF",
        formname: "Form-3",
        applicablelaw: "Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "monthly",
        section: "Preserve Form 2",
        priority: "high",
      },
      {
        sno: 4,
        activity: "PF return",
        formname: "Form-4",
        applicablelaw: "Insurance Act, 1998",
        acttype: "state",
        duedate: "monthly",
        period: "monthly",
        section: "Preserve Form 3",
        priority: "low",
      },
      {
        sno: 1,
        activity: "PF Remittance",
        formname: "PF Challan",
        applicablelaw: "Provident Fund & Miscellaneous Act, 1952",
        acttype: "Central",
        duedate: "15 of every Month",
        period: "Monthly",
        section: "Payment Receipt",
        priority: "High",
      },
      {
        sno: 2,
        activity: "PF Remittance",
        formname: "Form-2 / E-nomination",
        applicablelaw: "Employee State Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "Annual",
        section: "Preserve Form 2",
        priority: "Medium",
      },
      {
        sno: 3,
        activity: "PF",
        formname: "Form-3",
        applicablelaw: "Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "monthly",
        section: "Preserve Form 2",
        priority: "high",
      },
      {
        sno: 4,
        activity: "PF return",
        formname: "Form-4",
        applicablelaw: "Insurance Act, 1998",
        acttype: "state",
        duedate: "monthly",
        period: "monthly",
        section: "Preserve Form 3",
        priority: "low",
      },
      {
        sno: 1,
        activity: "PF Remittance",
        formname: "PF Challan",
        applicablelaw: "Provident Fund & Miscellaneous Act, 1952",
        acttype: "Central",
        duedate: "15 of every Month",
        period: "Monthly",
        section: "Payment Receipt",
        priority: "High",
      },
      {
        sno: 2,
        activity: "PF Remittance",
        formname: "Form-2 / E-nomination",
        applicablelaw: "Employee State Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "Annual",
        section: "Preserve Form 2",
        priority: "Medium",
      },
      {
        sno: 3,
        activity: "PF",
        formname: "Form-3",
        applicablelaw: "Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "monthly",
        section: "Preserve Form 2",
        priority: "high",
      },
      {
        sno: 4,
        activity: "PF return",
        formname: "Form-4",
        applicablelaw: "Insurance Act, 1998",
        acttype: "state",
        duedate: "monthly",
        period: "monthly",
        section: "Preserve Form 3",
        priority: "low",
      },{
        sno: 1,
        activity: "PF Remittance",
        formname: "PF Challan",
        applicablelaw: "Provident Fund & Miscellaneous Act, 1952",
        acttype: "Central",
        duedate: "15 of every Month",
        period: "Monthly",
        section: "Payment Receipt",
        priority: "High",
      },
      {
        sno: 2,
        activity: "PF Remittance",
        formname: "Form-2 / E-nomination",
        applicablelaw: "Employee State Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "Annual",
        section: "Preserve Form 2",
        priority: "Medium",
      },
      {
        sno: 3,
        activity: "PF",
        formname: "Form-3",
        applicablelaw: "Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "monthly",
        section: "Preserve Form 2",
        priority: "high",
      },
      {
        sno: 4,
        activity: "PF return",
        formname: "Form-4",
        applicablelaw: "Insurance Act, 1998",
        acttype: "state",
        duedate: "monthly",
        period: "monthly",
        section: "Preserve Form 3",
        priority: "low",
      },
      {
        sno: 1,
        activity: "PF Remittance",
        formname: "PF Challan",
        applicablelaw: "Provident Fund & Miscellaneous Act, 1952",
        acttype: "Central",
        duedate: "15 of every Month",
        period: "Monthly",
        section: "Payment Receipt",
        priority: "High",
      },
      {
        sno: 2,
        activity: "PF Remittance",
        formname: "Form-2 / E-nomination",
        applicablelaw: "Employee State Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "Annual",
        section: "Preserve Form 2",
        priority: "Medium",
      },
      {
        sno: 3,
        activity: "PF",
        formname: "Form-3",
        applicablelaw: "Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "monthly",
        section: "Preserve Form 2",
        priority: "high",
      },
      {
        sno: 4,
        activity: "PF return",
        formname: "Form-4",
        applicablelaw: "Insurance Act, 1998",
        acttype: "state",
        duedate: "monthly",
        period: "monthly",
        section: "Preserve Form 3",
        priority: "low",
      },
      {
        sno: 1,
        activity: "PF Remittance",
        formname: "PF Challan",
        applicablelaw: "Provident Fund & Miscellaneous Act, 1952",
        acttype: "Central",
        duedate: "15 of every Month",
        period: "Monthly",
        section: "Payment Receipt",
        priority: "High",
      },
      {
        sno: 2,
        activity: "PF Remittance",
        formname: "Form-2 / E-nomination",
        applicablelaw: "Employee State Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "Annual",
        section: "Preserve Form 2",
        priority: "Medium",
      },
      {
        sno: 3,
        activity: "PF",
        formname: "Form-3",
        applicablelaw: "Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "monthly",
        section: "Preserve Form 2",
        priority: "high",
      },
      {
        sno: 4,
        activity: "PF return",
        formname: "Form-4",
        applicablelaw: "Insurance Act, 1998",
        acttype: "state",
        duedate: "monthly",
        period: "monthly",
        section: "Preserve Form 3",
        priority: "low",
      },
      {
        sno: 1,
        activity: "PF Remittance",
        formname: "PF Challan",
        applicablelaw: "Provident Fund & Miscellaneous Act, 1952",
        acttype: "Central",
        duedate: "15 of every Month",
        period: "Monthly",
        section: "Payment Receipt",
        priority: "High",
      },
      {
        sno: 2,
        activity: "PF Remittance",
        formname: "Form-2 / E-nomination",
        applicablelaw: "Employee State Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "Annual",
        section: "Preserve Form 2",
        priority: "Medium",
      },
      {
        sno: 3,
        activity: "PF",
        formname: "Form-3",
        applicablelaw: "Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "monthly",
        section: "Preserve Form 2",
        priority: "high",
      },
      {
        sno: 4,
        activity: "PF return",
        formname: "Form-4",
        applicablelaw: "Insurance Act, 1998",
        acttype: "state",
        duedate: "monthly",
        period: "monthly",
        section: "Preserve Form 3",
        priority: "low",
      },
      {
        sno: 1,
        activity: "PF Remittance",
        formname: "PF Challan",
        applicablelaw: "Provident Fund & Miscellaneous Act, 1952",
        acttype: "Central",
        duedate: "15 of every Month",
        period: "Monthly",
        section: "Payment Receipt",
        priority: "High",
      },
      {
        sno: 2,
        activity: "PF Remittance",
        formname: "Form-2 / E-nomination",
        applicablelaw: "Employee State Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "Annual",
        section: "Preserve Form 2",
        priority: "Medium",
      },
      {
        sno: 3,
        activity: "PF",
        formname: "Form-3",
        applicablelaw: "Insurance Act, 1948",
        acttype: "Central",
        duedate: "Annual",
        period: "monthly",
        section: "Preserve Form 2",
        priority: "high",
      },
      {
        sno: 4,
        activity: "PF return",
        formname: "Form-4",
        applicablelaw: "Insurance Act, 1998",
        acttype: "state",
        duedate: "monthly",
        period: "monthly",
        section: "Preserve Form 3",
        priority: "low",
      },
]
export default Data;